export const PORT_TYPES = {
Video: {
  SDI: { label: "SDI", color: "#4a90e2" },
  HDMI: { label: "HDMI", color: "#e24a4a" },
    DisplayPort: { label: "DisplayPort", color: "#4ae24a" },
    NDI: { label: "NDI", color: "#e2e24a" },
    "USB-C Video": { label: "USB-C Video", color: "#e24ae2" },
    IP2110: { label: "IP2110", color: "#4ae2e2" },
    Ottico: { label: "Ottico", color: "#e2e24a" },
  },
  Audio: {
    XLR: { label: "XLR", color: "#4a90e2" },
    "Jack TRS": { label: "Jack TRS", color: "#e24a4a" },
    "Jack TS": { label: "Jack TS", color: "#4ae24a" },
    RCA: { label: "RCA", color: "#e24ae2" },
    Dante: { label: "Dante", color: "#4ae2e2" },
    "AES/EBU": { label: "AES/EBU", color: "#e2e24a" },
    MADI: { label: "MADI", color: "#4a90e2" },
    AES50: { label: "AES50", color: "#e24a4a" },
  },
  Network: {
    Ethernet: { label: "Ethernet", color: "#4ae24a" },
    "Ethernet + PoE": { label: "Ethernet + PoE", color: "#e24ae2" },
    SFP: { label: "SFP", color: "#4ae2e2" },
    MPO: { label: "MPO", color: "#e2e24a" },
  },
    
  Lighting: {
    "DMX 5p": { label: "DMX 5p", color: "#e2e24a" },
    "DMX 3p": { label: "DMX 3p", color: "#4a90e2" },
    ArtNet: { label: "ArtNet", color: "#e24a4a" },
    sACN: { label: "sACN", color: "#4ae24a" },
  },
  Power: {
    "CEE 16 Mono": { label: "CEE 16 Mono", color: "#e24ae2" },
    "CEE 32 Mono": { label: "CEE 32 Mono", color: "#4ae2e2" },
    "CEE 16 Penta": { label: "CEE 16 Penta", color: "#e2e24a" },
    "CEE 32 Penta": { label: "CEE 32 Penta", color: "#4a90e2" },
    "CEE 63 Penta": { label: "CEE 63 Penta", color: "#e24a4a" },
    "CEE 125 Penta": { label: "CEE 125 Penta", color: "#4ae24a" },
    "Powerlock 90mmq": { label: "Powerlock 90mmq", color: "#e24ae2" },
    "Powerlock 120mmq": { label: "Powerlock 120mmq", color: "#4ae2e2" },
    Socapex: { label: "Socapex", color: "#e2e24a" },
    "Civile EU": { label: "Civile EU", color: "#4a90e2" },
    "Civile Ita": { label: "Civile Ita", color: "#e24a4a" },
    Mazzeri: { label: "Mazzeri", color: "#4ae24a" },
  },
  Altro: {
    Custom: { label: "Custom", color: "#e24ae2" },
  },
};